### ISSUE TITLE
cross-wiki ROADMAP TRACKER

### ISSUE THREAD

**Issue by gorondan** [eth-protocol-fellows/protocol-studies#179]
## What content is missing?
A cross-wiki ROADMAP TRACKER that we can add to topic pages
## Related content in the wiki
I propose the following (minimal) format:
|Upgrade|URGE|Track|Cross-references|
|:---:|:---:|:---:|:---:|
|eg. ET|the Scourge|MEV track|intersection points with other upgrades eg. ePBS, PEPC, IL|

## Other relevant resources 
Should we add it to all topics, or just research (for ease of tracking parallel active research topics)?

**Comment by taxmeifyoucan** [comment]
This would mostly apply to pages under `research` because roadmap doesn't really touch topics outside of that. 

Also, it should be standard to add prerequisites and related content on top of the page everywhere. 

Fixed formatting of the markdown table, use an editing environment supporting markdown table formatting or a [formatter tool](https://github.com/nvuillam/markdown-table-formatter).

| Upgrade           | URGE        | Track     | Cross-references                                                 |
| ----------------- | ----------- | --------- | ---------------------------------------------------------------- |
| Execution Tickets | the Scourge | MEV track | intersection with other upgrades eg. ePBS, PEPC, IL (with links) |

**Comment by taxmeifyoucan** [comment]
Added to contributing.md https://github.com/eth-protocol-fellows/protocol-studies/commit/30d57dc1a06c8b15fd94f0b9caadaeb8ff0ce831
